# CodeRabbit Configuration
# For documentation, see: https://docs.coderabbit.ai/getting-started/configure-coderabbit

language: "en-US"
early_access: false

reviews:
  profile: "chill" # Options: "chill", "assertive", "comprehensive"
  request_changes_workflow: false
  high_level_summary: true
  path_filters:
    - "!**/node_modules/**"
    - "!.next/**"
    - "!public/**"
    - "!supabase/migrations/**" # You might want reviews on migrations, but often they are generated
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"

chat:
  enabled: true
